version: "3"
services:

  postgres:
    image: postgres:13.3
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rakukaji_db
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
    hostname: postgres
    restart: always
    stdin_open: true

  app:
    image: rakukaji-api
    restart: always
    container_name: "rakukaji-api"
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rakukaji_db
      - WORKERS=2
    entrypoint: ["./run.sh"]
    ports:
      - 8080:8080
    depends_on:
      - postgres
    tty: true